### ISSUE TITLE
etm dependency

### ISSUE THREAD

**Issue by pmakai** [gforge/Greg#11]
Greg seems to have dependency on the etm package, which was removed from CRAN. Using R version 4,.0.2, loading Greg gives the following error:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘etm’

Would be great if you could look into it!

**Comment by gforge** [comment]
I'm not getting any errors... The deps are:

```
Imports:
    Hmisc,
    stringr,
    rms,
    sandwich,
    stats,
    nlme,
    methods,
    htmlTable (>= 2.0.0),
    magrittr,
    knitr,
    Epi,
    utils,
    graphics,
    grDevices
Depends:
    forestplot,
    Gmisc (>= 1.0.3)
Suggests:
    boot,
    testthat,
    cmprsk,
    survival,
    dplyr,
    ggplot2,
    parallel,
    rmarkdown,
    rmeta
```

Can't find an etm package

**Comment by pmakai** [comment]
Thanks for the list! This seems to be an "upstream" problem. 

etm is a dependency for Epi, and that's the package causing the error. I've just tried to install Epi, but I can't. I will find the maintainer of that package, and see what can be done.
