### ISSUE TITLE
error in event status

### ISSUE THREAD

**Issue by cperk** [gforge/Greg#12]
Hello,

When I try to use timeSplitter() to split up my data for cox survival into small time increments, I get the following error:

Error in timeSplitter(Number_days_lived, by = 5, event_var = "event",  : 
  The event status should be among the levels in the event variable. Currently 'alive' is not found among 'dead', 'censored'.

It's because I had my regular cox survival model set up the regular way so that each individual was either "dead" or "censored"; the time variable was the number of days until death, so individuals that died before the end of the experiment received "dead" and those that made it to the end received "censored". It was implied that they were all alive until either they died or the experiment ended, so "alive" is not a status in the event variable. 

How do I get timeSplitter to work in this situation? Temporarily I've changed one individual's event status to "alive" just to get it to run, but won't be able to leave it that way.

Thanks!!!

-Carrie

**Comment by gforge** [comment]
Sorry but without a code example I need to close the issue due to lack of time
