### ISSUE TITLE
Error in library(Greg) : there is no package called 'Greg'

### ISSUE THREAD

**Issue by icehot1** [gforge/Greg#7]
Hello,

I can´t seem to add this package anymore. I am coming back to some code I was working on a couple years ago and its not letting me install the package. I´ve tried install.packages('Greg', dependencies=TRUE, repos='http://cran.rstudio.com/')

Then I get this:

Installing package into '/Users/stefanthorarensen/Library/R/3.1/library'
(as 'lib' is unspecified)

   package 'Greg' is available as a source package but not as a binary

Warning in install.packages :
  package 'Greg' is not available (for R version 3.1.2)
> 

Any suggestions would be greatly appreciated.

**Comment by gforge** [comment]
I think this is due to that the package was recently released and you are using an old R version. Try updating or installing from source `type="source"`.

**Comment by icehot1** [comment]
i updated the r version. i still get the same thing. what do you mean by installing from source

**Comment by gforge** [comment]
Thats odd, try just running `install.packages('Greg', type='source')` or if that doesn't work then try using devtools and install from the git repo
