### ISSUE TITLE
prPhEstimate' not found

### ISSUE THREAD

**Issue by gxb** [gforge/Greg#8]
Dear gforge
I use your function plotHR in the package of Greg and run the example from https://rdrr.io/cran/Greg/man/plotHR.html. But unfortunately, the program has the following error
"Error in fastDoCall(prPhEstimate, est_list) : 
  object 'prPhEstimate' not found"
I do not know whether it was because of a problem with my computer system or an R version of the problem. Could you please do me a favor to find an way to solve this problem?
Thank you very much for your time and consideration. I am looking forward to hearing from you. 
                                                                                       With kind regards, Yours sincerely,gxb
![_ud q5 lofci3ijox01i4](https://user-images.githubusercontent.com/7627831/38461645-5cf714e2-3b08-11e8-9338-2d31e7664277.png)

**Comment by gforge** [comment]
Works, old forgotten issue
