### ISSUE TITLE
How to edit the rownames

### ISSUE THREAD

**Issue by Meercat2** [gforge/Greg#9]
I am not able to edit the rownames after producing a forest plot with the function forestplotCombineRegrObj where I plotted HR (hazard ratio) for relevant variables from multiple cox models. 

I provided the reference.names for each model as well as the varialblesOfInterest.regexp. In the rows I want to remove the labels of the variablesOfInterest in the plot and just have the reference.names. Cannot find a neat way of doing this. 

Also, cannot find a function to add the confidence intervals to be shown, along with the HR. 

Any help would be welcome.

**Comment by gforge** [comment]
Do you have some example code to test?

**Comment by Meercat2** [comment]
This is my code. The models (multivariate cox regerssion models) being plotted are saved in my enviroment. 

forestplotCombineRegrObj(
  regr.obj = list(Model 1, Model 2, Model 3, Model 4, Model 5, Model 6),
  line.margin = 0.2,
  col=fpColors(box=c("red")),
  variablesOfInterest.regexp = "(Variable 1| Variable 2| Variable 3| Variable 4| Variable 5)",
  reference.names = c("Model 1", "Model 2", "Model 3", "Model 4", "Model 5", "Model 6"),
  title = "Multivariate cox regression analysis on subgroups of participants with Disease X",
  xlab = "Hazard ratio for endpoint Death",
  ci.vertices = TRUE, txt_gp=fpTxtGp(xlab = gpar(cex = 0.8, fontface = "bold", just = "center")),
  new_page= TRUE

**Comment by gforge** [comment]
Could you provide a full example that I can run and see?

**Comment by gforge** [comment]
I'm sorry but I'm closing this issue until I have a reproducible example that I can work with.
